#!/bin/bash
#PBS -N test
#PBS -l nodes=1:ppn=16
#PBS -q AM030_queue
#PBS -j oe
#################################################
#  File Name: test.pbs
#  
#  Author: zhengdongjian@tju.edu.cn
#  
#  Created Time: Thu 12 May 2016 06:12:50 AM CST
#  
#################################################

#================================================\
#生成可执行文件目录
OBJDIR=build
#数据文件夹
DATDIR=data

#串行程序名，源文件应为${serial}.cpp
serial=gauss
#并行程序名，源文件应为${parellel}.cpp
parellel=gauss_mt
#随机数生成器名，源文件${gen}.cpp
gen=generator

#数据规模(gen x gen的行列式)
gen_size=11
#数据范围(0~max-1的整数)
gen_max=3
#输入数据
input=input.txt

#核心数量
core_size=16

#输出重定向文件名
of1=serial.out
of2=parellel.out

#运行次数
if [ -z "$total" ]; then
    total=5
fi
#================================================/

if [ "$PBS_O_WORKDIR" != "" ]; then
    cd $PBS_O_WORKDIR
fi

# calculator = =
calc() {
    awk "BEGIN { print "$*" }"
}

#运行程序
#echo -e '\t>>> Serial Algorithm <<<' > $of1
#echo -e '\t>>> Parellel Algorithm <<<' > $of2
echo -n '' > $of1
echo -n '' > $of2
data_size=1
while [ $data_size -le $gen_size ]; do
    time_serial=0
    time_parellel=0
    i=1
    while [ $i -le $total ]; do
        #echo -e '-------- Round '$i' --------' >> $of1
        time_serial=$(($time_serial + `./$OBJDIR/$serial $DATDIR/$input $of1`))
        #echo '' >> $of1
        #echo '-------------------------------' >> $of1

        #echo -e '-------- Round '$i' --------' >> $of2
        time_parellel=$(($time_parellel + `./$OBJDIR/$parellel $DATDIR/$input $core_size`))
        #echo '' >> $of2
        #echo '-------------------------------' >> $of2

        i=$(($i + 1)) #i++
    done
    time_serial=`calc $time_serial/5.0`
    time_parellel=`calc $time_parellel/5.0`
    echo -e "Round_$data_size: \t$time_serial us" >> $of1
    echo -e "Round_$data_size: \t$time_parellel us" >> $of2
    data_size=$(($data_size + 1)) #data_size++
done

cat /proc/cpuinfo
