#!/bin/bash
#PBS -N test
#PBS -l nodes=1:ppn=1
#PBS -q AM030_queue
#PBS -j oe
#################################################
#  File Name: test.pbs
#  
#  Author: zhengdongjian@tju.edu.cn
#  
#  Created Time: Thu 12 May 2016 06:12:50 AM CST
#  
#################################################

#================================================\
#生成可执行文件目录
OBJDIR=build
#数据文件夹
DATDIR=data

#串行程序名，源文件应为${serial}.cpp
serial=gauss
#并行程序名，源文件应为${parellel}.cpp
parellel=gauss_mt

#输入数据
input=input.txt

#输出重定向文件名
of1=serial.out
of2=parellel.out

#运行次数
if [ -z "$total" ]; then
    total=10
fi
#================================================/

cd $PBS_O_WORKDIR

#运行程序
echo -e '\t>>> Serial Algorithm <<<' > $of1
echo -e '\t>>> Parellel Algorithm <<<' > $of2
i=1
while [ $i -le $total ]; do
    echo -e '-------- Round '$i' --------' >> $of1
    ./$OBJDIR/$serial $DATDIR/$input $of1
    echo '' >> $of1
    #echo '-------------------------------' >> $of1

    echo -e '-------- Round '$i' --------' >> $of2
    ./$OBJDIR/$parellel $DATDIR/$input $of2
    echo '' >> $of2
    #echo '-------------------------------' >> $of2

    i=$(($i + 1)) #i++
done
